on: push

jobs:
  with-color:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "::add-matcher::${{ github.workspace }}/matchers/error.json"
          echo "::add-matcher::${{ github.workspace }}/matchers/warning.json"

      - run: npm ci

      - run: npm test
        env:
          FORCE_COLOR: 3

  without-color:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "::add-matcher::${{ github.workspace }}/matchers/error.json"
          echo "::add-matcher::${{ github.workspace }}/matchers/warning.json"

      - run: npm ci

      - run: npm test
        env:
          NO_COLOR: 1
