on: push

jobs:
  with-color:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo "::add-matcher::${{ github.workspace }}/matchers/mixed.json"

      - run: npm ci

      - run: npm test
        env:
          FORCE_COLOR: 3

  without-color:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo "::add-matcher::${{ github.workspace }}/matchers/mixed.json"

      - run: npm ci

      - run: npm test
        env:
          NO_COLOR: 1
